### PR TITLE
Update README.md file:

### PR DESCRIPTION
**Pull request by roimenashe**
1. Add Maven configuration section (update Pom.xml).
2. Add numbering to headers - aligned with the table of contents.

### CODE REVIEW

**Review by reugn — CHANGES_REQUESTED** [review]
Table of contents links are broken.

**Comment by roimenashe** [comment]
> Table of contents links are broken.

Which one? I tested all of them I think, the links are x.x.x.- formatted on purpose.

**Comment by reugn** [comment]
https://github.com/aerospike/java-object-mapper/tree/readme-maven-configuration

**Comment by roimenashe** [comment]
> https://github.com/aerospike/java-object-mapper/tree/readme-maven-configuration

You are right, the dots doesn't work in urls only on Intelij readme.md preview.
Thanks, closed.

**Pull request closed without merging**
